baseURL = "https://pullrecast.dev"
title = 'PullreCast - Bate-papo descontraído com dois líderes técnicos apaixonados por tecnologia, colaboração e inovação, inspirador nas contribuições feitas em projetos open-source, para contribuir com a comunidade técnica convidando expoentes em diversas áreas para compartilhar suas experiências pessoais'
description = "Bate-papo descontraído com dois líderes técnicos apaixonados por tecnologia, colaboração e inovação, que se inspiraram no modelo das contribuições feitas atrás de um \"pull request\" em projetos open-source, para contribuir com a comunidade técnica convidando expoentes em diversas áreas para compartilhar suas experiências pessoais bem (e muitas vezes nem tanto) sucedidas, com objetivo de ajudar os profissionais das mais diversas carreiras de tecnologia a alavancarem sua [eminencia-tecnica]"
theme = "lynx"
# defaultContentLanguage = "pt"
languageCode = "pt"
enableEmoji = true
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true

googleAnalytics = "G-Z6QZB89BXW"


[Params]
  attribution = true
  keywords = "podcast, líder técnico, liderança técnica, tecnologia, colaboração, inovação, open-source, comunidade, comunidade técnica"

[author]
  name = "PullreCast"
  headline = "Potenciaze sua carreira com Inteligência Artificial"
  # headline = "Destravando sua Carreira Técnica e os Negócios com Inteligência Artificial"
  # headline = "Bate-papo descontraído com dois líderes técnicos apaixonados por tecnologia, colaboração e inovação, que se inspiraram no modelo das contribuições feitas atrás de um \"pull request\" em projetos open-source, para contribuir com a comunidade técnica convidando expoentes em diversas áreas para compartilhar suas experiências pessoais bem (e muitas vezes nem tanto) sucedidas, com objetivo de ajudar os profissionais das mais diversas carreiras de tecnologia a alavancarem sua eminência técnica!"
  image = "foto-dupla.png"
  links = [
    { mentoria = { href = "/mentoria", text = "Mentoria PotencializAI" } },
    # { loja = { href = "https://montink.com/camisetas-generativas?cat%5B71126%5D=71126", text = "Loja de Camisetas" } },
    { youtube = { href ="https://www.youtube.com/@pullrecast?sub_confirmation=1", text="Youtube" } },
    { instagram = "https://instagram.com/pullrecast" },
    { spotify = { href = "https://open.spotify.com/show/5zHeJgaZsj9WCMXfJoCVmD", text = "Spotify" } },
    #{ linkedin = { href="https://www.linkedin.com/groups/9509593/", text = "Grupo do Linkedin"} },
    #{ podcast = { href = "https://podcasts.apple.com/us/podcast/pull-recast/id1643158720", text = "Apple Podcasts" } },
    #{ google = { href = "https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy9iNDExYThjOC9wb2RjYXN0L3Jzcw", text = "Google Podcasts" } },
    #{ anchorfm = { href = "https://anchor.fm/pullrecast", text = "Anchor.fm" } },
    #{ github = "https://github.com/pullrecast-dev" },
    # { twitter = "https://twitter.com/pullrecast" }
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true


# languageCode = "en"
# defaultContentLanguage = "en"

# [params]
#     since = 2022
#     avatar = "/images/pullrecast-icon-color.png" #comment it to use gravatar
#     socialShare = true
#     subtitle = "Papos bem humorado sobre tecnologia." # site description
#     keywords = "" # site keywords

# [params.social]
#     Youtubechannel = "UC4FvW-Q6kVLeZuvhGb4txrQ"
#     GitHub = "pullrecast-dev"
#     Twitter = "pullrecast"
#     Instagram = "pullrecast"

# [params.share]
#     Twitter = true
#     Facebook = true
#     #Reddit = true
#     Linkedin = true
#     #Pinterest = true
#     #HackerNews = true
#     #Mix = true
#     #Tumblr = true
#     #VKontakte = true
#     #Douban = true
#     #Weibo = true
